In [2]:
import cv2
import numpy as np
import keras
from keras import models
from keras import utils
from keras.preprocessing import image
import os
import tensorflow as tf
import threading

In [3]:
model = models.load_model('cnn_10ep_ac1_Shaima_testac_94.keras')

In [3]:
#Capture video
#Extract frames
#Preprocess or resize frames
#predict frames

In [4]:
!mkdir test_imgs

mkdir: test_imgs: File exists


In [18]:
print(tf.__version__)

2.16.1


In [21]:
print(keras.__version__)

3.0.5


In [14]:
#Capture Image
import uuid
IMAGES_PATH = 'test_imgs'
cap = cv2.VideoCapture(0)
for imgnum in range(1):
    ret, frame = cap.read()
    imgname = os.path.join(IMAGES_PATH,'test.'+'{}.jpg'.format(str(uuid.uuid1())))
    cv2.imwrite(imgname, frame)
    cv2.imshow('frame', frame)
    test_im=frame
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [8]:
frame='./test_imgs/test.185b1662-df9e-11ee-9f57-7e09ada021c9.jpg'

In [9]:
image_rgb = cv2.cvtColor(test_im, cv2.COLOR_BGR2RGB)

In [10]:
resized_image = cv2.resize(image_rgb, (180, 180))

In [11]:
input_image = np.expand_dims(resized_image, 0)

In [12]:
prediction = np.array(model.predict(input_image))
print("pred")
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
pred
[[ 0.9975203 -2.61156    2.2320626  2.597943   2.4006493]]


In [5]:
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from keras import utils
import time
video = cv2.VideoCapture(0)
total_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
frame_rate = video.get(cv2.CAP_PROP_FPS)
start_time = time.time()

while True:
    _, frame = video.read()

    # Convert BGR to RGB
    # image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    # # plt.imshow(image_rgb)
    # print("image rgb")
    # print(image_rgb)

    frame_arr = utils.img_to_array(frame)
    
    # Resize the image
    resized_image = cv2.resize(frame_arr, (180, 180))
    # print("resized img")
    # print(resized_image)
    # plt.imshow(resized_image) #.numpy().astype(int))
    # plt.show()

    # Expand the dimensions from 3D to 4D (batch dimension)
    input_image = np.expand_dims(resized_image, 0)
    # print("input img")
    # print(input_image)

    # Make prediction
    prediction = np.array(model.predict(input_image))[0]
    print("pred")
    print(prediction)
    # Get predicted class index
    predicted_class_index = list(prediction).index(max(prediction))
    print("PCI")
    print(predicted_class_index)

    # Customize this part to your liking...
    if predicted_class_index == 0:
        print(f'Predicted class is Good')
    elif predicted_class_index == 1:
        print(f'Predicted class is Help')
    elif predicted_class_index == 2:
        print(f'Predicted class is Hungry')
    elif predicted_class_index == 3:
        print(f'Predicted class is Sorry')
    elif predicted_class_index == 4:
        print(f'Predicted class is Tired')

    cv2.imshow("Prediction", frame)

    key = cv2.waitKey(1)
    if key == ord('q'):
        break
end_time = time.time()

# Calculate total processing time
total_time = end_time - start_time

# Calculate frame rate
calculated_frame_rate = total_frames / total_time

print("Frame rate (from video metadata):", frame_rate)
print("Calculated frame rate:", calculated_frame_rate)

video.release()
cv2.destroyAllWindows()


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
pred
[ 1.0144665 -2.5972242  2.1858573  2.587514   2.4052606]
PCI
3
Predicted class is Sorry
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
pred
[ 2.9693134  -1.0210882   0.87577325  1.0516453   2.200291  ]
PCI
0
Predicted class is Good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
pred
[ 4.1209974  -0.02820246  0.05554486  0.4356761   1.523539  ]
PCI
0
Predicted class is Good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
pred
[ 5.097461    0.5704095  -0.37631086  0.01607123  1.0716916 ]
PCI
0
Predicted class is Good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
pred
[ 5.5405726   0.6792521  -0.39823186 -0.12520991  0.9571285 ]
PCI
0
Predicted class is Good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
pred
[ 6.0774927   0.73115945 -0.33667976 -0.25100467  0.755918  ]
PCI
0
Predicted class is Good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
pred
[ 6.155471    0.61569154 -0.25573304 -0.2621184   0.98880106]
PCI
0
Predicted class is Good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
pred
[ 6.4792404   0.