In [1]:
import cv2
import numpy as np
import tensorflow as tf
from keras import models

In [2]:
# Load the saved model
model = models.load_model('cnn_Shaima-test-1.keras')

In [4]:
# Capture video
video_capture = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = video_capture.read()

    # Convert the frame to grayscale
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Resize the frame to match the input size of the model
    frame_resized = cv2.resize(frame_gray, (180, 180))

    # Expand dimensions to match the input shape of the model
    frame_input = np.expand_dims(frame_resized, axis=0)
    frame_input = np.expand_dims(frame_input, axis=-1)  # Add channel dimension

    # Predict the class of the frame using the loaded model
    predictions = model.predict(frame_input)

    # Get the predicted class index
    predicted_class_index = np.argmax(predictions)

    # Get the class label based on the predicted class index
    class_names = ['no', 'thankyou', 'yes'] #'fine', 'hello', 
    predicted_class_label = class_names[predicted_class_index]

    # Display the predicted class label on the frame
    cv2.putText(frame, predicted_class_label, (10, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

    # Print the predicted class label in the terminal
    print(predictions)
    print("Predicted class label:", predicted_class_label)

    # Display the frame
    cv2.imshow('Video', frame)

    # Check if the 'q' key was pressed to exit the loop
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture object and close all windows
video_capture.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 34ms/step
[[0.06161797 0.25531647 0.40164807 0.12276308 0.15865439]]
Predicted class label: yes
1/1 [==============================] - 0s 14ms/step
[[9.4495796e-02 3.2917100e-03 5.5232358e-01 3.7844665e-04 3.4951046e-01]]
Predicted class label: yes
1/1 [==============================] - 0s 13ms/step
[[1.12011366e-01 1.77102978e-03 6.07649446e-01 2.37683824e-04
  2.78330505e-01]]
Predicted class label: yes
1/1 [==============================] - 0s 14ms/step
[[1.09878935e-01 1.85831811e-03 6.10090673e-01 1.62915792e-04
  2.78009176e-01]]
Predicted class label: yes
1/1 [==============================] - 0s 14ms/step
[[1.1894334e-01 1.4856388e-03 6.3882852e-01 1.4727601e-04 2.4059524e-01]]
Predicted class label: yes
1/1 [==============================] - 0s 12ms/step
[[1.1460645e-01 1.3926609e-03 6.5021676e-01 1.2087267e-04 2.3366329e-01]]
Predicted class label: yes
1/1 [==============================] - 0s 13ms/step
[[1.1574711e-01 1.2637983e-03 6