In [2]:
import cv2
import numpy as np
from PIL import Image
from keras import models
import os
import tensorflow as tf

In [19]:
CHECKPOINT_FILEPATH = 'training_1/cp.ckpt'
CHECKPOINT_DIR = os.path.dirname(CHECKPOINT_FILEPATH)

In [21]:
model = models.load_model('cnn_10ep_ac96.h5')
#model.load_weights(CHECKPOINT_FILEPATH)

In [22]:
video = cv2.VideoCapture(0)

while True:
        _, frame = video.read()

        #Convert the captured frame into RGB
        im = Image.fromarray(frame, 'RGB')
        
        #Resizing into dimensions you used while training
        im = tf.image.resize(im, (180,180))
        print(im.shape)
        im.numpy().astype(int)
        # img_array = np.array(im)

        # #Expand dimensions to match the 4D Tensor shape.
        # img_array = np.expand_dims(img_array, axis=0)
        # print(img_array)
        # #Calling the predict function using keras
        # prediction = model.predict(img_array)#
        prediction = np.array(model.predict(np.expand_dims(im, 0)))
        print(prediction)
        predicted_class_index = np.argmax(prediction)
        #Customize this part to your liking...
        if predicted_class_index==0: 
            print(f'Predicted class is Hello')
        elif predicted_class_index==1:
            print(f'Predicted class is Fine')
        elif predicted_class_index==2:
            print(f'Predicted class is No')
        elif predicted_class_index==3:
            print(f'Predicted class is Thank You')
        elif predicted_class_index==4:
            print(f'Predicted class is Yes')

        cv2.imshow("Prediction", frame)
        key=cv2.waitKey(1)
        if key == ord('q'):
                break
video.release()
cv2.destroyAllWindows()


(180, 180, 3)
1/1 [==============================] - 0s 54ms/step
[[ 3.6288621  9.398832  -0.7368979 -6.7223234  3.0528698]]
Predicted class is Fine
(180, 180, 3)
1/1 [==============================] - 0s 15ms/step
[[ 3.5970404  9.423755  -0.6798835 -6.7277255  3.0842738]]
Predicted class is Fine
(180, 180, 3)
1/1 [==============================] - 0s 16ms/step
[[ 3.6132944   9.415877   -0.69485474 -6.72461     3.0470827 ]]
Predicted class is Fine
(180, 180, 3)
1/1 [==============================] - 0s 14ms/step
[[ 3.5897217  9.22813   -0.5641059 -6.560827   2.879028 ]]
Predicted class is Fine
(180, 180, 3)
1/1 [==============================] - 0s 16ms/step
[[ 3.4559987  9.147706  -0.3934614 -6.4409785  2.8646235]]
Predicted class is Fine
(180, 180, 3)
1/1 [==============================] - 0s 15ms/step
[[ 3.3754005   9.13133    -0.28412974 -6.382869    2.821706  ]]
Predicted class is Fine
(180, 180, 3)
1/1 [==============================] - 0s 18ms/step
[[ 3.4270234  9.142731  -0.279

KeyboardInterrupt: 