In [1]:
import cv2
import numpy as np
import tensorflow as tf
from keras import models

In [2]:
# Load the saved model
model = models.load_model('cnn_Ananki_acc95_testac89_gray.h5')

In [4]:
# Capture video
video_capture = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = video_capture.read()

    # Convert the frame to grayscale
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Resize the frame to match the input size of the model
    frame_resized = cv2.resize(frame_gray, (180, 180))

    # Expand dimensions to match the input shape of the model
    frame_input = np.expand_dims(frame_resized, axis=0)
    frame_input = np.expand_dims(frame_input, axis=-1)  # Add channel dimension

    # Predict the class of the frame using the loaded model
    predictions = model.predict(frame_input)

    # Get the predicted class index
    predicted_class_index = np.argmax(predictions)

    # Get the class label based on the predicted class index
    class_names = ['no', 'thankyou', 'yes'] #'fine', 'hello', 
    predicted_class_label = class_names[predicted_class_index]

    # Display the predicted class label on the frame
    cv2.putText(frame, predicted_class_label, (10, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

    # Print the predicted class label in the terminal
    print(predictions)
    print("Predicted class label:", predicted_class_label)

    # Display the frame
    cv2.imshow('Video', frame)

    # Check if the 'q' key was pressed to exit the loop
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture object and close all windows
video_capture.release()
cv2.destroyAllWindows()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[[0.9924446  0.00170908 0.00584636]]
Predicted class label: no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[0.99174726 0.00196565 0.00628716]]
Predicted class label: no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[0.99256027 0.00171363 0.00572614]]
Predicted class label: no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[0.9924786  0.00178992 0.00573146]]
Predicted class label: no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[0.99181634 0.00200201 0.00618166]]
Predicted class label: no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[0.9922517  0.00190921 0.00583903]]
Predicted class label: no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[0.9914649 0.0019305 0.0066046]]
Predicted class label: no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[0.9918515  0.00169349 0.00645495]]
Predicted class label: no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[0.9905556  0.00189477 0.00754966]]
Predicted class label: no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[0.98848253 0.00237687 0.0091405 ]]
Predicted class lab